version: '3.3'

services:
  redis:
    image: redis:6
    ports:
      - "6379:6379"
  elasticsearch:
    image: elasticsearch:7.6.2
    ports:
      - "9200:9200"
    volumes:
      - ./storage/app:/usr/share/elasticsearch/data
    environment:
      - "discovery.type=single-node"
      - "bootstrap.memory_lock=true"
  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.2
    links:
      - elasticsearch:elasticsearch
    ports:
      - "5601:5601"
    volumes:
      - ./storage/app:/usr/share/kibana/config/kibana.yml

